spring:
  config:
    activate:
      on-profile : local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/pedia
    username: Yang
    password: 0000!


  jpa:
    hibernate:
      ddl-auto: none