spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/est_form_sec
    username: root
    password: rudcjs

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1068707518231-6l58kl77u7d13vfd68fk97lb1i6oj2cg.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            client-name: Naver
            client-id: 7r5_uupRwzDEer9d_N_i
            client-secret: Zf83y3NiQ7
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - name
              - email

          kakao:
            client-name: Kakao
            client-id: 6a56a91d8da4c7d36d474a29be1efa10
            client-secret: VUv43k75CI7YO8b3qa66gnJ18rthlHi6
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-name-attribute: response
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

custom:
  jwt:
    validation:
      access: 600000
      refresh: 86400000
    secret:
      app-key: 4B398FBF0C39348DFD0E7188B151F3F734ACCD37006BCA207077FCA52701E3D5
      origin-key: cdcb4cfb-3fd2-4a9c-85df-8d8545238fc4



