spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/pedia
    username: Yang
    password: 0000!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: DEBUG